services:
  app:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen3:0.6b
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data:

